# Generated by Django 3.1.14 on 2022-04-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=20)),
                ('fathers_name', models.CharField(max_length=100)),
                ('fathers_occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('mothers_name', models.CharField(max_length=100)),
                ('mothers_occupation', models.CharField(blank=True, max_length=30, null=True)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('TRANSGENDER', 'TRANSGENDER'), ('OHTER', 'OTHER')], max_length=100)),
                ('category', models.CharField(choices=[('SC', 'SC'), ('ST', 'ST'), ('OBC', 'OBC'), ('GENERAL', 'GENERAL'), ('MINORITY', 'MINORITY'), ('OHTER', 'OTHER')], max_length=50)),
                ('address', models.CharField(max_length=180)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pin', models.PositiveIntegerField()),
                ('course', models.CharField(choices=[('B.tech', 'B.tech'), ('M.tech', 'M.tech'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('Diploma', 'Diploma')], max_length=100)),
                ('lateral', models.CharField(choices=[('REGULAR', 'REGUALR'), ('LATERAL ENTRY', 'LATERAL ENTRY')], max_length=50)),
                ('session_start', models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035')], max_length=50)),
                ('session_end', models.CharField(choices=[('2015', '2015'), ('2016', '2016'), ('2017', '2017'), ('2018', '2018'), ('2019', '2019'), ('2020', '2020'), ('2021', '2021'), ('2022', '2022'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('2029', '2029'), ('2030', '2030'), ('2031', '2031'), ('2032', '2032'), ('2033', '2033'), ('2034', '2034'), ('2035', '2035')], max_length=50)),
                ('mark10_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('mark10_total', models.PositiveIntegerField(blank=True, null=True)),
                ('mark12_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('mark12_total', models.PositiveIntegerField(blank=True, null=True)),
                ('mark_diploma_obtain', models.PositiveIntegerField(blank=True, null=True)),
                ('mark_diploma_total', models.PositiveIntegerField(blank=True, null=True)),
                ('mark_graduation_obtained', models.PositiveIntegerField(blank=True, null=True)),
                ('mark_graduation_total', models.PositiveIntegerField(blank=True, null=True)),
                ('department', models.CharField(blank=True, choices=[('MBA department', 'MBA department'), ('Computer Science department', ' Computer Science department'), ('Electrical department', 'Electrical department'), ('Mechanical Department', 'Mechanical Department'), ('Civil Department', 'Civil Department'), ('Electronic and Engineering Department', 'Electronic and Engineering Department')], max_length=50, null=True)),
                ('mobile', models.PositiveIntegerField()),
                ('mobile2', models.PositiveIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='d/1')),
                ('sign', models.ImageField(blank=True, null=True, upload_to='d/8')),
                ('Adhaar', models.FileField(blank=True, null=True, upload_to='d/2')),
                ('Adhaar_no', models.CharField(blank=True, max_length=12, null=True)),
                ('pan', models.FileField(blank=True, null=True, upload_to='d/3')),
                ('pan_no', models.CharField(blank=True, max_length=10, null=True)),
                ('domicile', models.FileField(blank=True, null=True, upload_to='d/9')),
                ('caste', models.FileField(blank=True, null=True, upload_to='d/3')),
                ('income', models.FileField(blank=True, null=True, upload_to='d/4')),
                ('total_income', models.CharField(blank=True, choices=[('Below 1 lac ', 'Below 1 lac'), ('1 lac - 2 lac', '1 lac - 2 lac'), ('2 lac - 4 lac', '2 lac - 4 lac'), ('Above 4 lac', 'Above 4 lac')], max_length=100, null=True)),
                ('charactor_certificate', models.FileField(blank=True, null=True, upload_to='d/5')),
                ('mark10', models.FileField(blank=True, null=True, upload_to='d/6')),
                ('mark12', models.FileField(blank=True, null=True, upload_to='d/7')),
                ('mark_diploma', models.FileField(blank=True, null=True, upload_to='d/7')),
                ('mark_graduation', models.FileField(blank=True, null=True, upload_to='d/8')),
                ('scholar_credit', models.CharField(blank=True, choices=[('NO', 'NO'), ('YES', 'YES')], default='NO', max_length=50)),
                ('scholar_credit_ammount', models.PositiveIntegerField(blank=True, null=True)),
                ('number_of_installment', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=50, null=True)),
                ('installment_1_ammount', models.PositiveIntegerField(blank=True, null=True)),
                ('installment_1_date', models.DateField(blank=True)),
                ('installment_2_ammount', models.PositiveIntegerField(blank=True, null=True)),
                ('installment_2_date', models.DateField(blank=True)),
                ('installment_3_ammount', models.PositiveIntegerField(blank=True, null=True)),
                ('installment_3_date', models.DateField(blank=True)),
                ('installment_4_ammount', models.PositiveIntegerField(blank=True, null=True)),
                ('installment_4_date', models.DateField(blank=True)),
                ('installment_5_ammount', models.PositiveIntegerField(blank=True, null=True)),
                ('installment_5_date', models.DateField(blank=True)),
                ('refrenced_by', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
