# Generated by Django 3.1.14 on 2022-05-19 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_data',
            name='installment_1_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='installment_2_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='installment_3_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='installment_4_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student_data',
            name='installment_5_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
